-- Deprecated as a runnable script.
-- Use the Supabase migration instead:
--   supabase/migrations/20260717162600_create_contacts.sql
--
-- Apply with:
--   npx supabase db push
-- or paste that migration file into the Supabase Dashboard → SQL Editor.
